name: Deploy

on:
    push:
        branches:
            - v2-master
jobs:
    build:
        runs-on: ubuntu-latest
        name: Deploy

        steps:
            - name: Set env vars (common)
              run: |
                  echo "REMOTE_APP_FOLDER=~/apps/did-siop-rp-web-min" >> $GITHUB_ENV
                  echo "REMOTE_APP_NAME=did-siop-rp-web-min" >> $GITHUB_ENV
            - name: Set env vars (prod)
              if: endsWith(github.ref, '/master-v2')
              run: |
                  echo "REMOTE_APP_PORT=4005" >> $GITHUB_ENV
                  echo "REMOTE_APP_ENV=prod" >> $GITHUB_ENV
                  echo "REMOTE_HOST="${{ secrets.SSH_HOST_PROD }} >> $GITHUB_ENV

            - name: Checkout code
              uses: actions/checkout@v2

            - name: Compress codebase
              run: |
                  tar -zcvf project.tar.gz ./*
            - name: Copy project to server
              uses: nogsantos/scp-deploy@master
              with:
                  src: ./project.tar.gz
                  host: ${{ env.REMOTE_HOST }}
                  remote: ${{ env.REMOTE_APP_FOLDER }}
                  port: ${{ secrets.SSH_PORT }}
                  user: ${{ secrets.SSH_USER }}
                  key: ${{ secrets.SSH_KEY }}

            - name: SSH Decompress & Run
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ env.REMOTE_HOST }}
                  username: ${{ secrets.SSH_USER }}
                  key: ${{ secrets.SSH_KEY }}
                  port: ${{ secrets.SSH_PORT }}
                  script: |
                      cd ${{ env.REMOTE_APP_FOLDER }}
                      tar xvzf ./project.tar.gz --directory ./
                      rm ./project.tar.gz
                      yarn install
                      pm2 delete ${{ env.REMOTE_APP_NAME }}_${{ env.REMOTE_APP_ENV }}_${{ env.REMOTE_APP_PORT }}
                      pm2 start yarn --name ${{ env.REMOTE_APP_NAME }}_${{ env.REMOTE_APP_ENV }}_${{ env.REMOTE_APP_PORT }} -- start
